<?xml version="1.0" encoding="UTF-8"?>
<definitions name="UAService"
 targetNamespace="urn:UAService"
 xmlns:tns="urn:UAService"
 xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:ns="urn:UAService"
 xmlns:SOAP="http://schemas.xmlsoap.org/wsdl/soap/"
 xmlns:MIME="http://schemas.xmlsoap.org/wsdl/mime/"
 xmlns:DIME="http://schemas.xmlsoap.org/ws/2002/04/dime/wsdl/"
 xmlns:WSDL="http://schemas.xmlsoap.org/wsdl/"
 xmlns="http://schemas.xmlsoap.org/wsdl/">

<types>

 <schema targetNamespace="urn:UAService"
  xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:ns="urn:UAService"
  xmlns="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="unqualified"
  attributeFormDefault="unqualified">
  <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
  <!-- operation request element -->
  <element name="currentTime">
   <complexType>
    <sequence>
    </sequence>
   </complexType>
  </element>
  <!-- operation response element -->
  <element name="currentTimeResponse">
   <complexType>
    <sequence>
     <element name="response" type="xsd:long" minOccurs="1" maxOccurs="1"/>
    </sequence>
   </complexType>
  </element>
 </schema>

</types>

<message name="currentTimeRequest">
 <part name="parameters" element="ns:currentTime"/>
</message>

<message name="currentTimeResponse">
 <part name="parameters" element="ns:currentTimeResponse"/>
</message>

<portType name="UAServicePortType">
 <operation name="currentTime">
  <documentation>Service definition of function ns__currentTime</documentation>
  <input message="tns:currentTimeRequest"/>
  <output message="tns:currentTimeResponse"/>
 </operation>
</portType>

<binding name="UAService" type="tns:UAServicePortType">
 <SOAP:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
 <operation name="currentTime">
  <SOAP:operation soapAction=""/>
  <input>
     <SOAP:body parts="parameters" use="literal"/>
  </input>
  <output>
     <SOAP:body parts="parameters" use="literal"/>
  </output>
 </operation>
</binding>

<service name="UAService">
 <documentation>gSOAP 2.7.9e generated service definition</documentation>
 <port name="UAService" binding="tns:UAService">
  <SOAP:address location="http://caesar/UAService"/>
 </port>
</service>

</definitions>
